### ISSUE TITLE
display_modes not supported

### ISSUE THREAD

**Issue by todostreaming** [fabled/bmd-tools#14]
Hi, first of all I have to congratulate for your interesting tools.
Now the question:
How can I get the settings (.r1000......) for an unsupported display_modes[ ] ?
I would like to have /* DMODE_720x576i_30 */ what is the usual PAL and for /* DMODE_720x480i_29_97 */ what is the usual NTSC.
Could you help me to find them ?

Thanks in advance and best regards. 
TS

**Comment by fabled** [comment]
Steps to do it:
1) Record some video using the official drivers in desired video format
2) Stop drivers / reconnect to another computer with bmd-tools
3) Run bmd-streamer with "-v -v" and it'll dump the chip initialization values
4) Post the values here

**Comment by todostreaming** [comment]
Thanks for your prompt reply. I'll try to do it and post the values here. However I would like to confirm these steps with more details.
I guess, I will need 2 computers, one with the official drivers (Desktop Video for Linux) and another with bmd-streamer (as I have, w/o official drivers for having no issues). 
1) I will use the 1st pc for recording the desired video format using Media Express for Linux.
2) I have to stop the drivers in the 1st pc while recording. (modprobe -r blackmagic) ? Then disconnect the USB from the 1st pc and connect it to the 2nd one.
3) Run just: ./bmd-streamer -v -v   (no more options needed ? input or whatever ?). And I will have a dump with the hex values.

Thanks in advance and best regards,
TS
